services:
  backend:
    container_name: backend_gosell
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - REDIS_URI=${REDIS_URI}
      - API_PORT=${API_PORT}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend/static/images/avatars:/app/static/images/avatars
      - ./backend/static/images/adverts:/app/static/images/adverts
      - .env:/app/.env
    depends_on:
      - mongo
      - redis
    networks:
      - backend
      - frontend

  mongo:
    image: mongo:7.0
    container_name: mongo_gosell
    restart: always
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  redis:
    image: redis:7.2
    container_name: redis_gosell
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    networks:
      - backend

  frontend:
    container_name: frontend_gosell
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - backend
    environment:
      API_URL: ${API_URL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_API_URL_IMG: ${NEXT_PUBLIC_API_URL_IMG}
    networks:
      - frontend

volumes:
  mongo_data:
  redis_data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge